[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#38BDF8"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#181B24"
textColor = "#F3F4F6"
font = "sans serif"
